"""Kid map sprites (Eren, Mikasa, Armin) as ASCII pixel art.

Letters map to FE8 map-sprite palette indices per character (see COLORS).
Frames are drawn 11 wide x 13 tall (feet on row 11, shadow on row 12).
"""

# Palette index meaning in FE8 unit palettes:
# 1-3 faction dark/mid/light, 4 brown-grey, 5 tan, 6 cream skin, 7-10 faction main,
# 11 accent (red on blue units), 12 yellow, 13 shadow, 14 white, 15 outline.

BASE = {'.': 0, 'O': 15, 'S': 6, 's': 5, 'D': 13, 'W': 14, 'w': 3, 'B': 15, 'E': 15}

COLORS = {
    'eren':   dict(BASE, H=4, h=15, P=5, p=4, C=14, c=3, X=4, x=4),
    'mikasa': dict(BASE, H=15, h=1, P=1, p=7, C=6, c=5, X=11, x=11),
    'armin':  dict(BASE, H=12, h=5, P=4, p=15, C=5, c=4, X=5, x=4),
}

# ---------------------------------------------------------------- Eren
EREN = {
'front': [
"...OOOOO...",
"..OHOHHHO..",
".OHHHHOHHO.",
".OHSHSHSHO.",
".OSESSSESO.",
"..OSSsSSO..",
"..OCCsCCO..",
".OCCCCCCCO.",
".OSOCCcOSO.",
"..OOPPPOO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'front_step': [
"...OOOOO...",
"..OHOHHHO..",
".OHHHHOHHO.",
".OHSHSHSHO.",
".OSESSSESO.",
"..OSSsSSO..",
"..OCCsCCO..",
".OCCCCCCCO.",
".OSOCCcOSO.",
"..OOPPPOO..",
"...OPOOB...",
"...OBO.....",
"..DDDDDDD..",
],
'side': [
"...OOOOO...",
"..OHHOHHO..",
".OHHHHHHHO.",
".OHHHSSSHO.",
".OHHSSESO..",
"..OHSSSsO..",
"...OCSCO...",
"..OCCCCO...",
"..OCCSCO...",
"...OPPO....",
"...OPPO....",
"...OBBO....",
"..DDDDDD...",
],
'side_step': [
"...OOOOO...",
"..OHHOHHO..",
".OHHHHHHHO.",
".OHHHSSSHO.",
".OHHSSESO..",
"..OHSSSsO..",
"...OCSCO...",
"..OCCCCCO..",
".OSOCCOSO..",
"...OPPPO...",
"..OPOOPO...",
"..OBO.OBO..",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
"..OHHHHHO..",
"..OCCSCCO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'back_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
"..OHHHHHO..",
"..OCCSCCO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...BOPOO...",
".....OBO...",
"..DDDDDDD..",
],
}

# ---------------------------------------------------------------- Mikasa
MIKASA = {
'front': [
"...OOOOO...",
"..OHHHHHO..",
".OHHhHHhHO.",
".OHSSSSSHO.",
".OHESSSEHO.",
".OHSSsSSHO.",
".OHXXXXXHO.",
".OXXxXXXXO.",
".OSOCCCOSO.",
"..OPPPPPO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'front_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHhHHhHO.",
".OHSSSSSHO.",
".OHESSSEHO.",
".OHSSsSSHO.",
".OHXXXXXHO.",
".OXXxXXXXO.",
".OSOCCCOSO.",
"..OPPPPPO..",
"...OPOOB...",
"...OBO.....",
"..DDDDDDD..",
],
'side': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHSSSO.",
".OHHHSSESO.",
".OHHHSSSsO.",
".OHXXXXXO..",
"..OXXCCO...",
"..OCCSCO...",
"..OPPPPO...",
"...OPPO....",
"...OBBO....",
"..DDDDDD...",
],
'side_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHSSSO.",
".OHHHSSESO.",
".OHHHSSSsO.",
".OHXXXXXO..",
"..OXXCCCO..",
".OSOCCOSO..",
"..OPPPPPO..",
"..OPOOPO...",
"..OBO.OBO..",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OXXXXXXXO.",
".OCXXxXXCO.",
".OSOCCCOSO.",
"..OPPPPPO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'back_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OXXXXXXXO.",
".OCXXxXXCO.",
".OSOCCCOSO.",
"..OPPPPPO..",
"...BOPOO...",
".....OBO...",
"..DDDDDDD..",
],
}

# ---------------------------------------------------------------- Armin
ARMIN = {
'front': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHESSSEHO.",
".OHSSsSSHO.",
"..OOSSSOO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'front_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHESSSEHO.",
".OHSSsSSHO.",
"..OOSSSOO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...OPOOB...",
"...OBO.....",
"..DDDDDDD..",
],
'side': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHHHHSESO.",
".OHHHSSSsO.",
"..OOOSSO...",
"..OCCCCO...",
"..OCCSCO...",
"...OPPO....",
"...OPPO....",
"...OBBO....",
"..DDDDDD...",
],
'side_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHHHHSESO.",
".OHHHSSSsO.",
"..OOOSSO...",
"..OCCCCCO..",
".OSOCCOSO..",
"...OPPPO...",
"..OPOOPO...",
"..OBO.OBO..",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
".OHHHHHHHO.",
"..OOOOOOO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...OPOPO...",
"...OBOBO...",
"..DDDDDDD..",
],
'back_step': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHhHHhHO.",
".OHHHHHHHO.",
".OHHHHHHHO.",
"..OOOOOOO..",
".OCCCCCCCO.",
".OSOCcCOSO.",
"..OOPPPOO..",
"...BOPOO...",
".....OBO...",
"..DDDDDDD..",
],
}

KIDS = {'eren': EREN, 'mikasa': MIKASA, 'armin': ARMIN}
