"""Shiganshina townsfolk and Carla, hand-drawn 11x18 (16x32 SMS)."""
BASE = {'.': 0, 'O': 15, 'S': 6, 's': 5, 'E': 15, 'D': 13,
        'T': 5, 't': 4,          # tan cloth
        'A': 14, 'a': 3,         # white apron / shirt (shade takes the faction tint)
        'V': 8, 'v': 7,          # faction-coloured vest / skirt
        'b': 15, 'B': 4}
COLORS = {
    'man':   dict(BASE, H=4, h=15),
    'woman': dict(BASE, H=5, h=4, K=9),     # K kerchief (faction)
    'carla': dict(BASE, H=15, h=4),
}

MAN = {
'front': [
"...OOOOO...",
"..OHHHHHO..",
".OHHhHHHHO.",
".OHSSSSShO.",
".OSESSSESO.",
"..OSSsSSO..",
"..OAOSOAO..",
".OVVAAAVVO.",
"OVVVAAAVVvO",
"OSOVAAAVOSO",
"OSOVVAVVOSO",
".ObbbbbbbO.",
".OTTTTTTtO.",
"..OTTOTtO..",
"..OTTOTtO..",
"..OTTOTtO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
'side': [
"...OOOOO...",
"..OHHHHHO..",
".OhHHHHHHO.",
".OhHHHSSSO.",
".OhHHSSESO.",
"..OHSSSsO..",
"...OASAO...",
"..OVAAAVO..",
"..OVAAVvO..",
"..OVSAVvO..",
"..OVVSVO...",
"..ObbbbO...",
"...OTTtO...",
"...OTTtO...",
"...OTTtO...",
"...OTTtO...",
"...ObbbbO..",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHHHHHHHO.",
"..OHHHHHO..",
"..OASSSAO..",
".OVVVVVVVO.",
"OVVVVVVVVvO",
"OSOVVVVVOSO",
"OSOVVVVVOSO",
".ObbbbbbbO.",
".OTTTTTTtO.",
"..OTTOTtO..",
"..OTTOTtO..",
"..OTTOTtO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
}

WOMAN = {
'front': [
"...OOOOO...",
"..OKKKKKO..",
".OKKKKKKKO.",
".OHSSSSSHO.",
".OSESSSESO.",
"..OSSsSSO..",
"..OTOSOTO..",
".OTTTTTTTO.",
"OTTAAAAATtO",
"OSOAAAAAOSO",
"OTOAAAAAOtO",
".OTAAAAATO.",
".OVAAAAAVO.",
".OVVAAAVvO.",
".OVVVVVVvO.",
"..OVVVVvO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
'side': [
"...OOOOO...",
"..OKKKKKO..",
".OKKKKKKKO.",
".OKKHHSSSO.",
".OKHHSSESO.",
"..OHSSSsO..",
"...OTSTO...",
"..OTTTTAO..",
"..OTTTAAO..",
"..OTSTAAO..",
"..OTTTAAO..",
"..OVVVAAO..",
"..OVVVVAO..",
"..OVVVVvO..",
"..OVVVVvO..",
"...OVVvO...",
"...ObbbO...",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OKKKKKO..",
".OKKKKKKKO.",
".OKKKKKKKO.",
".OHHKKKHHO.",
"..OHHHHHO..",
"..OTSSSTO..",
".OTTTTTTTO.",
"OTTTAATTTtO",
"OSOTTTTTOSO",
"OTOTTTTTOtO",
".OTTTTTTTO.",
".OVVVVVVVO.",
".OVVVVVVvO.",
".OVVVVVVvO.",
"..OVVVVvO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
}

CARLA = {
'front': [
"...OOOOO...",
"..OHHHHHO..",
".OHHhHhHHO.",
".OHSSSSSHO.",
".OHESSSEHO.",
"..OSSsSShO.",
"..OTOSOThO.",
".OTTTTTTThO",
"OTTAAAAATtO",
"OSOAAAAAOSO",
"OTOAAAAAOtO",
".OTAAAAATO.",
".OTAAAAATO.",
".OTTAAATtO.",
".OTTTTTTtO.",
"..OTTTTtO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
'side': [
"...OOOOO...",
"..OHHHHHO..",
".OhHHHHHHO.",
".OhHHHSSSO.",
".OhHHSSESO.",
".OhhHSSSsO.",
".OhOTSTO...",
"..OTTTTAO..",
"..OTTTAAO..",
"..OTSTAAO..",
"..OTTTAAO..",
"..OTTTAAO..",
"..OTTTTAO..",
"..OTTTTtO..",
"..OTTTTtO..",
"...OTTtO...",
"...ObbbO...",
"..DDDDDDD..",
],
'back': [
"...OOOOO...",
"..OHHHHHO..",
".OHHHHHHHO.",
".OHHHHHHHO.",
".OHHHHHHhO.",
"..OHHHHhhO.",
"..OTSSShhO.",
".OTTTTTThhO",
"OTTTAATTThO",
"OSOTTTTTOSO",
"OTOTTTTTOtO",
".OTTTTTTTO.",
".OTTTTTTTO.",
".OTTTTTTtO.",
".OTTTTTTtO.",
"..OTTTTtO..",
"..ObbObbO..",
".DDDDDDDDD.",
],
}


def steps(fr):
    """Add step frames: the trouser/skirt hem lifts on one side."""
    out = dict(fr)
    f = fr['front']
    out['front_step'] = f[:15] + [f[15], "..ObbOOOO..", ".DDDDDDDDD."] if True else f
    out['back_step'] = fr['back'][:15] + [fr['back'][15], "..ObbOOOO..", ".DDDDDDDDD."]
    s = fr['side']
    out['side_step'] = s[:14] + ["..OTTTTtO..".replace('T', s[14][3]).replace('t', s[14][6]) if False else s[14], ".OTTOOtO...".replace('T', s[14][3]).replace('t', s[14][6]), ".ObbO.ObO..", "..DDDDDDD.."]
    return out


FRAMES = {'man': steps(MAN), 'woman': steps(WOMAN), 'carla': steps(CARLA)}
