"""Shiganshina townsfolk and Carla, 16 wide x 22 tall (16x32 SMS), same scale as adults_hd."""
BASE = {'.': 0, 'O': 15, 'S': 6, 's': 5, 'E': 15, 'D': 13,
        'T': 5, 't': 4,          # tan cloth
        'A': 14, 'a': 3,         # white apron / shirt
        'V': 8, 'v': 7,          # faction-coloured vest / skirt
        'b': 15, 'B': 4}
COLORS = {
    'man':   dict(BASE, H=4, h=15),
    'woman': dict(BASE, H=5, h=4, K=9),
    'carla': dict(BASE, H=15, h=4, K=4),
}

MAN = {
'front': [
"......OOOO......",
".....OHHHHO.....",
"....OHHHHHHO....",
"...OHHHHHHHHO...",
"...OHhHHHHHhO...",
"...OHSSSSSShO...",
"...OSESSSSESO...",
"...OSSSSSSSSO...",
"....OSSssSSO....",
".....OSSSSO.....",
"....OVOAAOVO....",
"...OVVVAAVVVO...",
"..OVVVVAAVVvvO..",
"..OVVVVAAVVvvO..",
"..OSOVVAAVvOSO..",
"..OSObbbbbbOSO..",
"....OTTTTTtO....",
"....OTTOOTtO....",
"....OTTOOTtO....",
"....OTTOOTtO....",
"....ObbOObbO....",
"...DOOODDOOOD...",
],
'side': [
"......OOOOO.....",
".....OHHHHHO....",
"....OHHHHHHHO...",
"....OhHHHHHHHO..",
"....OhHHHHSSSO..",
"....OhHHHSSSSO..",
"....OhHHSSSESO..",
".....OHSSSSSSO..",
".....OhSSSssO...",
"......OSSSSO....",
".....OVVAAO.....",
"....OVVVVAVO....",
"....OVVVVVvO....",
"....OVSVVvvO....",
"....OVSVVvvO....",
"....ObbbbbbO....",
".....OTTTTtO....",
".....OTTTTtO....",
".....OTTOTtO....",
".....OTTOTtO....",
".....ObbObbbO...",
"....DDDDDDDDD...",
],
'back': [
"......OOOO......",
".....OHHHHO.....",
"....OHHHHHHO....",
"...OHHHHHHHHO...",
"...OHHHHHHHHO...",
"...OHhHHHHhHO...",
"...OHHHhhHHHO...",
"...OhHHHHHHhO...",
"....OHHHHHHO....",
".....OSSSSO.....",
"....OVVVVVVO....",
"...OVVVVVVVVO...",
"..OVVVVVVVVvvO..",
"..OVVVVVVVVvvO..",
"..OSOVVVVVvOSO..",
"..OSObbbbbbOSO..",
"....OTTTTTtO....",
"....OTTOOTtO....",
"....OTTOOTtO....",
"....OTTOOTtO....",
"....ObbOObbO....",
"...DOOODDOOOD...",
],
}

WOMAN = {
'front': [
"......OOOO......",
".....OKKKKO.....",
"....OKKKKKKO....",
"...OKKKKKKKKO...",
"...OHKKKKKKHO...",
"...OHSSSSSShO...",
"...OSESSSSESO...",
"...OSSSSSSSSO...",
"....OSSssSSO....",
".....OSSSSO.....",
"....OTOAAOTO....",
"...OTTTAATTTO...",
"..OTTAAAAAAttO..",
"..OTTAAAAAAttO..",
"..OSOAAAAAAOSO..",
"..OSOAAAAAaOSO..",
"...OVVAAAAaVvO..",
"...OVVAAAAaVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVvvO..",
"....OObbObbOO...",
"...DDOODDOODD...",
],
'side': [
"......OOOOO.....",
".....OKKKKKO....",
"....OKKKKKKKO...",
"....OKKKKKKKKO..",
"....OhKKKHSSSO..",
"....OhHHHSSSSO..",
"....OhHHSSSESO..",
".....OHSSSSSSO..",
".....OhSSSssO...",
"......OSSSSO....",
".....OTTAAO.....",
"....OTTTTAAO....",
"....OTTTTAAO....",
"....OTSTTAaO....",
"....OTSTTAaO....",
"....OVVVVAaO....",
"....OVVVVAaO....",
"....OVVVVVvO....",
"...OVVVVVVvO....",
"...OVVVVVVvvO...",
"....OObbObbbO...",
"...DDDDDDDDDD...",
],
'back': [
"......OOOO......",
".....OKKKKO.....",
"....OKKKKKKO....",
"...OKKKKKKKKO...",
"...OKKKKKKKKO...",
"...OHKKKKKKHO...",
"...OHHHKKHHHO...",
"...OhHHHHHHhO...",
"....OHHHHHHO....",
".....OSSSSO.....",
"....OTTTTTTO....",
"...OTTTTTTTTO...",
"..OTTTAAAATttO..",
"..OTTTTAATTttO..",
"..OSOTTTTTtOSO..",
"..OSOVVVVVvOSO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVvvO..",
"....OObbObbOO...",
"...DDOODDOODD...",
],
}

# Carla: long dark hair in a low ponytail over her right shoulder,
# tan blouse, long faction-coloured skirt, white apron.
CARLA = {
'front': [
"......OOOO......",
".....OHHHHO.....",
"....OHHHHHHO....",
"...OHHHHHHHHO...",
"...OHHhHHhHHO...",
"...OHSSSSSSHO...",
"...OHESSSSESO...",
"...OHSSSSSSSO...",
"...OHOSssSSO....",
"...OHHOSSSO.....",
"...OHHTAATO.....",
"...OHHTAATTO....",
"..OTHHAAAATtO...",
"..OTHHAAAAAtO...",
"..OSOHAAAAAOSO..",
"..OSOAAAAAaOSO..",
"...OVVAAAAaVvO..",
"...OVVAAAAaVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVvvO..",
"....OObbObbOO...",
"...DDOODDOODD...",
],
'side': [
"......OOOOO.....",
".....OHHHHHO....",
"....OHHHHHHHO...",
"....OHHHHHHHHO..",
"...OHhHHHHSSSO..",
"...OHhHHHSSSSO..",
"...OHhHHSSSESO..",
"...OHHHSSSSSSO..",
"...OHHhOSSssO...",
"...OHHO.OSSO....",
"....OHOTTAO.....",
"....OHTTTAAO....",
"....OTTTTAAO....",
"....OTSTTAaO....",
"....OTSTTAaO....",
"....OVVVVAaO....",
"....OVVVVAaO....",
"....OVVVVVvO....",
"...OVVVVVVvO....",
"...OVVVVVVvvO...",
"....OObbObbbO...",
"...DDDDDDDDDD...",
],
'back': [
"......OOOO......",
".....OHHHHO.....",
"....OHHHHHHO....",
"...OHHHHHHHHO...",
"...OHHHHHHHHO...",
"...OHhHHHHhHO...",
"...OHHHhhHHHO...",
"...OhHHHHHHhO...",
"....OHHHHHHO....",
".....OHHHHO.....",
"....OTTHHOTO....",
"...OTTTHHTTTO...",
"..OTTTTHHTTttO..",
"..OTTTTHHTTttO..",
"..OSOTTKKTtOSO..",
"..OSOVVAAVvOSO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVVvO..",
"...OVVVVVVVvvO..",
"....OObbObbOO...",
"...DDOODDOODD...",
],
}


def steps(t):
    t = dict(t)
    f = t['front']
    t['front_step'] = f[:20] + [f[20][:8] + "ObbO....", f[21][:8] + "DDDDD..."]
    b = t['back']
    t['back_step'] = b[:20] + [b[20][:8] + "ObbO....", b[21][:8] + "DDDDD..."]
    s = list(t['side'])
    s[20] = s[20][:4] + "ObbO.ObbO" + s[20][13:]
    s[21] = "...DDDDDDDDDDD.."
    t['side_step'] = s
    return t


FRAMES = {'man': steps(MAN), 'woman': steps(WOMAN), 'carla': steps(CARLA)}
for _t in FRAMES.values():
    for _f in _t.values():
        assert len(_f) == 22 and all(len(r) == 16 for r in _f), _f
